apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: acourse
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: registry.dev.afsmtddso.com/acourse-harbor-project/app@sha256:f1e30a67d39b77d42471a4f89bef8f3195eddd64ef0b18ce0f531ea624b33431
        ports:
        - containerPort: 5000
