apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: acourse
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: registry.dev.afsmtddso.com/acourse-harbor-project/db@sha256:b15159254197edd35698f77c05ad136eff444434ce6f72ef89ef76f1d6e8b4c9
        ports:
        - containerPort: 5432
